services:
  # Default service using host networking for better printer connectivity
  stickyprint:
    build: .
    container_name: stickyprint
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      # Configuration file
      - ./config.json:/app/config.json:ro
      # Optional: bind mount for logs
      - ./logs:/app/logs
      # System directories needed for avahi/dbus
      - /var/run/dbus:/var/run/dbus:rw
    environment:
      # Alternative: use environment variables instead of config file
      - STICKYPRINT_AUTO_DISCOVER=true
      - STICKYPRINT_MANUAL_IP=
      - STICKYPRINT_FONT_SIZE=12
      - STICKYPRINT_MARGIN=10
      - STICKYPRINT_LINE_SPACING=1.2
      - STICKYPRINT_CALENDAR_ENTITY=calendar.family
      - STICKYPRINT_DISCOVERY_TIMEOUT=30
      - STICKYPRINT_HA_URL=http://homeassistant.local:8123
      - STICKYPRINT_HA_TOKEN=your_token_here
      - STICKYPRINT_PORT=8099

  # Alternative service with bridge networking (if needed for specific setups)
  stickyprint-bridge:
    build: .
    container_name: stickyprint-bridge
    restart: unless-stopped
    ports:
      - "8099:8099"
    privileged: true
    volumes:
      - ./config.json:/app/config.json:ro
      - ./logs:/app/logs
      - /var/run/dbus:/var/run/dbus:rw
    environment:
      - STICKYPRINT_AUTO_DISCOVER=true
      - STICKYPRINT_MANUAL_IP=
      - STICKYPRINT_FONT_SIZE=12
      - STICKYPRINT_MARGIN=10
      - STICKYPRINT_LINE_SPACING=1.2
      - STICKYPRINT_CALENDAR_ENTITY=calendar.family
      - STICKYPRINT_DISCOVERY_TIMEOUT=30
      - STICKYPRINT_HA_URL=http://homeassistant.local:8123
      - STICKYPRINT_HA_TOKEN=your_token_here
      - STICKYPRINT_PORT=8099
    networks:
      - stickyprint-network
    profiles:
      - bridge-network

networks:
  stickyprint-network:
    driver: bridge
